name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Simulando entrega (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            **.py
            README.md